
    create table cliente (
       id integer generated by default as identity,
        cpf varchar(120) not null,
        data_cadastro timestamp,
        nome varchar(120) not null,
        primary key (id)
    );

    create table servico_prestado (
       id integer generated by default as identity,
        data date,
        descricao varchar(150) not null,
        valor decimal(19,2),
        id_cliente integer,
        primary key (id)
    );

    create table usuario (
       id integer generated by default as identity,
        senha varchar(255),
        login varchar(255),
        primary key (id)
    );

    alter table usuario 
       add constraint UK_pm3f4m4fqv89oeeeac4tbe2f4 unique (login);

    alter table servico_prestado 
       add constraint FKesbc6v6g25jp341vhqu1r42qi 
       foreign key (id_cliente) 
       references cliente;
